services:
  backend:
    environment:
      NODE_ENV: production
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    command: sh -c "npm install && npm start"

  frontend:
    environment:
      NODE_ENV: production
    volumes:
      - ./frontend/world-chat:/app
      - frontend_node_modules:/app/node_modules
    command: sh -c "npm install && npm run build && npm start"
